### ISSUE TITLE
The results of the experiments varied widely

### ISSUE THREAD

**Issue by wawjwyy123** [cai525/Transformer4SED#4]
Hi，why do I finish running cd./exps/mat-sed/base
./train.sh, the result is only psds1=0.036, psds2=0.404? How to get similar results psds1=0.587, psds2=0.79? Do I need to change the default epoch?

**Comment by wawjwyy123** [comment]
Is there a problem with my data? The default data is 32k, my data is 16k, I only have 16k and 44k data at present

**Comment by cai525** [comment]
Obviously, the sampling rate is a significant  setting for audio signal processing. Please make sure your settings are consistent with the original paper to get correct results. You can use [this script](https://github.com/cai525/Transformer4SED/blob/main/src/utils/resample.py) to resample the wavs.
