### ISSUE TITLE
How to use my own dataset (如何使用自己的数据集)

### ISSUE THREAD

**Issue by ZhenxiongTang** [cai525/Transformer4SED#5]
您好，首先感谢您的贡献，我是SED新手，我想知道如何在自己的数据集上进行训练而后推理，而不是DESED数据集，是否可以解答我这个问题？
> Hello, first of all, thank you for your contribution. I am new to sound event detection task and I want to know how to train and then infer on my own dataset instead of the DESED dataset. Can you answer this question for me?

**Comment by cai525** [comment]
感谢您对我们工作的关注。对于这个问题，你需要熟悉DESED数据集的标注方式(参考meta文件夹)。你可以将你自己的数据集。按照DESED数据集的方式，生成对应的标注文件，并且在配置文件中修改数据集路径，以及事件类别、采样率等其他和数据集有关的变量。

**Comment by ZhenxiongTang** [comment]
感谢您的及时回复，期待您新的成果，祝您生活愉快。
