### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by 2502912390** [cai525/Transformer4SED#6]
What version of Python are you using? The requirements.txt file does not specify it, and I have failed to configure the environment with Python 3.8 and 3.10. Please let me know the version of Python you are using.

**Comment by cai525** [comment]
Hi. You can find the detailed description of the running environment in [this issue](https://github.com/cai525/Transformer4SED/issues/3), including the python Version.

**Comment by 2502912390** [comment]
Thank you very much.
